### PR TITLE
Fixed primary screen detector & more features

### PR DESCRIPTION
**Pull request by ColonelBundy**
- Added: Sound support
- Added: Optional auto cleanup
- Fixed: Primary screen detector
- Bonus: Made jslint happy

### CODE REVIEW

**Comment by cgrossde** [comment]
I'm currently working on a new release. Where did you get the notification.wav? Is it free for commercial use?

**Comment by ColonelBundy** [comment]
Yes its free for commercial use, I will try to find it and provide a link with details.

UPDATE:
Sounds: http://rcptones.com/dev_tones/ its the "beep_short_on" 
License: http://creativecommons.org/licenses/by/3.0/us/

Have a great day :)

**Comment by cgrossde** [comment]
Thank you for the PR and fast reply. Version 1.0.0 is released :) 

https://github.com/cgrossde/nw-notify/releases/tag/1.0.0

**Comment by ColonelBundy** [comment]
Great! you will see lots of more pr's from me, that's for sure. I really really like this project.

Thank you!

**Pull request merged**
