### PR TITLE
port for 0.13

### PR DESCRIPTION
**Pull request by pansinm**
[Migrate from 0.12 to 0.13](http://docs.nwjs.io/en/latest/For%20Users/Migration/From%200.12%20to%200.13/)

### CODE REVIEW

**Comment by cgrossde** [comment]
Thanks for your PR. I just tried to run the tests under 0.12 and 0.13. No notifications show up. Did you tests this? If so which version and OS did u use?

**Comment by pansinm** [comment]
I can run the test with win10 & nw v0.14.7, I'll check it for 0.13 later

**Comment by pansinm** [comment]
Window.open return undefined under version 0.13. and 'loaded' event not triggered at all. but 0.14.7 works well.

**Comment by cgrossde** [comment]
On Mac OS it didn't work on 0.12, 0.13, 0.18.7. I have yet to investigate why. If you want you can take over nw-notify. I don't have much time lately to keep maintaining it. I would leave a note in the readme which points to your fork and take a look at how to give you access to npm.

**Comment by pansinm** [comment]
thank you.
I can't let it work for all version greater than 0.13 , and  I have no time to maintain a new branch, so I close this PQ

**Pull request closed without merging**
